export const ITASK_QUERY_REPOSITORY = 'ITASK_QUERY_REPOSITORY';
export const IRESUME_QUERY_REPOSITORY = 'IRESUME_QUERY_REPOSITORY';
export const ITASK_COMMAND_REPOSITORY = 'ITASK_COMMAND_REPOSITORY';
export const ICHECK_POINT_COMMAND_REPOSITORY =
  'ICHECK_POINT_COMMAND_REPOSITORY';
